### ISSUE TITLE
I never installed it yet it appears in my catalougue and it wont be removed

### ISSUE THREAD

**Issue by Hermanallan** [kaio/ibus-table#80] opened 2023-03-20 10:29 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or videos**
If applicable, add screenshots or videos to help explain your problem.

**ibus-table version?**
Open the ibus-table setup tool and click on the `About` button (Or check the version of the installed package, for example using `rpm -q ibus-table` on rpm based distribtions).

**ibus version?**
Run `ibus version` (Or check the version of the installed package, for example using `rpm -q ibus` on rpm based distribtions).

**Distribution and version?**
For example Fedora 35, Ubuntu 20.04, FreeBSD 11.1, …

**Desktop and version?**
For example Gnome 3, KDE, XFCE, i3, ...

**Xorg or Wayland?**
You can check this with `echo $XDG_SESSION_TYPE`

**Additional context**

**Comment by mike-fabian** [comment] 2023-03-20 19:04
Please explain in  more detail what the problem is.
You want to uninstall ibus-table? That's easy. How exactly depends on the distribution you are using.

**Comment by mike-fabian** [comment] 2023-06-26 11:17
Closing because there was no answer.

**Closed by mike-fabian** 2023-06-26 11:17 UTC
Labels: bug
